title: Lendingclub Project
author: HyounJun Park
email: junparkh@domain.com
author2:  Fernando Trias
email2:  fernando@trias.org
author3: Roger Iliffe
email3: rogerjiliffe@gmail.com
author4: Siyuan Yin
email4: siy422@g.harvard.edu




description: > # this means to ignore newlines until "twitter_username:"
    This is the final project for CS109A: Harvard University.
remote_theme: jekyll/minima
# social links
# twitter_username: jekyllrb
# github_username:  jekyll
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
#mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - menu1.md
# - menu2.md
# - menu3.md
# - menu4.md



# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
